releases/20201029083752/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
    get "standards", to: "users/registrations#new_standard"
    post "standards", to: "users/registrations#create_standard"
  end

  root to: "posts#index"

  # 画像一覧ページ
  get "posts/image" => "posts#image"

  resources :posts do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :charts, only: :index

  resources :calories, only: :index

  resources :calendars, only: :index

  resources :relationships, only: [:create, :destroy]
end

releases/20201029083752/app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

releases/20201029083752/app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.build(post_id: params[:post_id])
    @like.save
    @likeCounts = Like.where(post_id: params[:post_id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    @likeCounts = Like.where(post_id: params[:post_id])
  end
end

releases/20201029083752/app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

releases/20201029083752/app/views/likes/_like.html.haml
- if user_signed_in?
  - if current_user.already_liked?(post)
    = link_to post_like_path(post_id: post.id, id: post.likes[0].id), method: :delete, remote: true, id: 'delete-like', class: 'like-button' do
      %i.fa.fa-heart
    = post.likes.count
  - else
    = link_to post_likes_path(post.id), method: :post, remote: true, id: 'like', class: 'like-button' do
      %i.fa.fa-heart-o
    = post.likes.count
- else
  = link_to post_path(post.id), class: 'like-button' do
    %i.fa.fa-heart-o 
  = post.likes.count

releases/20201029083752/app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

releases/20201029083752/app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");