releases/20201029081621/releases/20201026220654/releases/20201017104702/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    get 'standards', to: 'users/registrations#new_standard'
    post 'standards', to: 'users/registrations#create_standard'
  end

  root to: "posts#index"

  # 画像一覧ページ
  get "posts/image" => "posts#image"

  resources :posts do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :charts, only: :index

  resources :calories, only: :index

  resources :calendars, only: :index

  resources :relationships, only: [:create, :destroy]

end

releases/20201029081621/releases/20201026220654/releases/20201017104702/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :user
  
  validates :food, presence: true
  validates :calorie, presence: true

  mount_uploader :image, ImageUploader
end

releases/20201029081621/releases/20201026220654/releases/20201017104702/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create, :destroy]
  
  def index
    @posts = Post.all.includes(:user).order("created_at DESC").page(params[:page]).per(5)
    @post = Post.new
    @user = current_user
    @sampleuser = User.find_by(id: 2)
    
    # グラフに必要なデータを表示させるための変数を条件分岐
    if user_signed_in?
      @user = current_user
      @calorie_sum = Post.where(user_id: current_user.id, created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).sum(:calorie)
      gon.today_sum = @calorie_sum
      @standard = Standard.find_by(user_id: current_user.id)
      @calorie_standard = @standard.calorie
      gon.standard = @calorie_standard
      if @calorie_sum >= @calorie_standard
        @difference = @calorie_sum - @calorie_standard
      else
        @difference = @calorie_standard - @calorie_sum
      end
    else
      @sampleuser = User.find_by(id: 2)
      @calorie_sum = Post.where(user_id: @sampleuser.id, created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).sum(:calorie)
      gon.today_sum = @calorie_sum
      @standard = Standard.find_by(user_id: @sampleuser.id)
      @calorie_standard = @standard.calorie
      gon.standard = @calorie_standard
      if @calorie_sum >= @calorie_standard
        @difference = @calorie_sum - @calorie_standard
      else
        @difference = @calorie_standard - @calorie_sum
      end
    end
  end
  

  def create
    @post = Post.new(post_params)
    # 今日の日付を取得(simple_calendarのため)
    @post[:start_time] = Date.today.strftime('%Y-%m-%d')
    if @post.save
      redirect_back(fallback_location: root_path) # なぜredirect_to root_pathじゃダメなのかわかってない
    else
      @posts = Post.includes(:user)
      flash.now[:alert] = '必須項目をしてください。' # フラッシュメッセージが出るか確認する
      redirect_back(fallback_location: root_path)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
    @like = Like.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_back(fallback_location: root_path) 
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
    else
      flash.now[:alert] = 'エラーが発生しました。'
      render :edit
    end
  end

  def image
    @sampleuser = User.find_by(id: 2)
    if user_signed_in?
      @posts = Post.where(user_id: current_user.id).where.not(image: nil).order("created_at DESC")
    else
      @posts = Post.where(user_id: @sampleuser.id).where.not(image: nil).order("created_at DESC")
    end
  end

  private
  def post_params
    params.require(:post).permit(:food, :calorie, :protein, :fat, :carbo, :text, :image, :weight, :start_time).merge(user_id: current_user.id)
  end

end

releases/20201029081621/releases/20201026220654/releases/20201017104702/app/helpers/posts_helper.rb
module PostsHelper
end

releases/20201029081621/releases/20201026220654/releases/20201017104702/app/views/posts/_main.html.haml
.main
  .section
    .calorie_chart.col-sm-9
      .calorie_graph
        %canvas(id="myChart2" width="700" height="100")
        :javascript
          var ctx = document.getElementById('myChart2').getContext('2d');
          var myChart = new Chart(ctx, {
              type: 'horizontalBar',
              data: {
                  labels: ['１日のカロリー目安：' + gon.standard, '今日のカロリー合計：' + gon.today_sum],
                  datasets: [{
                      label: '今日のカロリーを確認',
                      data: [gon.standard, gon.today_sum],
                      backgroundColor: [
                          'rgba(255, 99, 132, 0.2)',
                          'rgba(54, 162, 235, 0.2)',
                      ],
                      borderColor: [
                          'rgba(255,99,132,1)',
                          'rgba(54, 162, 235, 1)',
                      ],
                      borderWidth: 1
                  }]
              },
              options: {
                  scales: {
                      xAxes: [{
                          ticks: {
                              beginAtZero:true,
                              suggestedMin: 50,
                              suggestedMax: 100
                          }
                      }]
                  }
              }
          });
      .today_calorie
        %p
        - if user_signed_in?
          - if @calorie_standard >= @calorie_sum
            今日食べてOKなのはあと
            = link_to charts_path(current_user.id), class: 'difference' do
              = @difference
            カロリーです
          - else
            = link_to charts_path(current_user.id), class: 'difference' do
              = @difference
            オーバーしています
        - else
          - if @calorie_standard >= @calorie_sum
            今日はあと
            = link_to charts_path(@sampleuser.id), class: 'difference' do
              = @difference
            カロリーです
          - else
            = link_to charts_path(@sampleuser.id), class: 'difference' do
              = @difference
            オーバーしています
      %hr
    .new-post.col-sm-9
      = form_with model: @post, id: 'new_post' do |f|
        .input-box
          %table.col-sm-12
            %thead
              %tr
                %th.food Food
                %th.calorie Calorie
                %th.protein P タンパク質
                %th.fat F 脂質
                %th.carbo C 炭水化物
            %tbody.table-body.table-line
              %tr
                %td 
                  = f.text_field :food, placeholder: '例）サラダ'
                %td 
                  = f.number_field :calorie, step: '0.1', placeholder: '例）200'
                %td 
                  = f.number_field :protein, step: '0.1', placeholder: '例）30'
                %td 
                  = f.number_field :fat, step: '0.1', placeholder: '例）20'
                %td 
                  = f.number_field :carbo, step: '0.1', placeholder: '例）50'
                -# %td.icon-plus
                -#   %i.fa.fa-plus-circle.fa-2x{class: 'plus-button'}
                -# %td.icon-minus
                -#   %i.fa.fa-minus-circle.fa-2x{class: 'minus-button'}
          .text.col-sm-12
            = f.text_area :text, placeholder: 'なにたべた？', class: 'post-textarea'
          .icon
            .image-upload
              -# %i.fas.fa-image.fa-2x
              = f.file_field :image, class: 'image_upload'
          .weight-and-btn
            .weight
              体重
              = f.number_field :weight, step: '0.1', placeholder: '例）70'
              kg
            .btn-square
              = f.submit '投稿する', class: 'post-btn'
    .posts
      = render @posts
      = paginate(@posts)

releases/20201029081621/releases/20201026220654/releases/20201017104702/app/views/posts/_post.html.haml
= link_to "/posts/#{post.id}" do
  .post
    .post-box.col-sm-9
      .upper-post
        .upper-post__user-name
          = link_to user_path(post.user_id) do
            = post.user.name
        .upper-post__date
          %time(datetime="#{post.created_at}")= time_ago_in_words(post.created_at)+"前"
      .lower-post
        .weight
        - if post.weight.present?
          体重
          = post.weight
          kg
        %table.col-sm-12
          %thead
            %tr
              %th FOOD
              %th Calorie
              %th P タンパク質
              %th F 脂質
              %th C 炭水化物
          %tbody.table-body
            %tr
              %td 
                = post.food
              %td 
                = post.calorie
              %td 
                = post.protein
              %td 
                = post.fat
              %td 
                = post.carbo
        - if post.text.present?
          .text.col-sm-12
            = post.text
        - if post.image.present?
          = image_tag post.image.url, class: 'post-image'
        %ul.more_list
          %li
            = link_to "/posts/#{post.id}", method: :get do
              %i.fas.fa-info-circle
              %span.edit 詳細
          %li
            = link_to "/posts/#{post.id}/edit", method: :get do
              %i.fa.fa-edit
              %span.edit 編集
          %li
            = link_to post_path(post.id), method: :delete do
              %i.fa.fa-trash
              %span.trash 削除          
          %li{id: "likes_buttons_#{post.id}", class: 'likes_buttons'}
            = render partial: 'likes/like', locals: {post: post, likes: @likes}
          %li
            = link_to "/posts/#{post.id}" do
              %i.fa.fa-commenting-o
            = post.comments.count

releases/20201029081621/releases/20201026220654/releases/20201017104702/app/views/posts/edit.html.haml
.new-post
  = form_with model: @post do |f|
    .input-box
      %table
        %thead
          %tr
            %th FOOD
            %th Calorie
        %tbody
          %tr
            %td 
              = f.text_field :food, placeholder: '例）サラダチキン'
            %td 
              = f.number_field :calorie, placeholder: '例）200'
      %table
        %thead
          %tr
            %th P
            %th F
            %th C
        %tbody
          %tr
            %td 
              = f.number_field :protein, placeholder: '例）30'
            %td 
              = f.number_field :fat, placeholder: '例）20'
            %td 
              = f.number_field :carbo, placeholder: '例）50'
      %table
        %thead
          %tr
            %th 今日のひとこと
        %tbody
          %tr
            %td 
              = f.text_area :text, placeholder: 'なにたべた？'
      %table
        %thead
          %tr
            %th 3枚までアップロードできます
        %tbody
          %tr
            %td 
              = icon('fas', 'image', class: 'icon')
              = f.file_field :image
      .submit-btn
        = f.submit '投稿する'

-# どうやって編集したあと一覧画面に再投稿するんだっけ？一覧画面へのpathはどのように設定するんだっけ？
-# 「投稿する」ボタンを押したら、一覧画面に飛んで、投稿内容が変わっているようにしたい
-# チーム開発の方は、なんで商品情報編集したら、showにいくようになってるんだっけ？どこでそういう設定してるんだっけ？
-# コンソールにエラーが出ていた。そうか、updateアクションか。controllerのupdateアクションの設定か。editのform_withはupdateアクションに飛ぶのか。

releases/20201029081621/releases/20201026220654/releases/20201017104702/app/views/posts/image.html.haml
.image-container
  .image-wrapper
    .images
    - @posts.each do |post|
      = image_tag post.image.url, class: "my-images"
  .home
    = link_to 'ホームに戻る', root_path, class: 'home-btn'

releases/20201029081621/releases/20201026220654/releases/20201017104702/app/views/posts/index.html.haml
.container-fluid
  .row.row-0
    .col-sm-3
      = render "side_bar"
    .col-sm-9
      = render "main"

releases/20201029081621/releases/20201026220654/releases/20201017104702/app/views/posts/new.html.haml
%body
  %header
  .contents
    .container
      = form_with model: @post do |f|
        食べたもの
        = f.text_field :food, placeholder: '例）サラダチキン'
        カロリー
        = f.number_field :calorie, placeholder: '例）200'
        タンパク質(P)
        = f.number_field :protein, placeholder: '例）30'
        脂質(F)
        = f.number_field :fat, placeholder: '例）20'
        炭水化物(C)
        = f.number_field :carbo, placeholder: '例）50'
        今日のつぶやき
        = f.text_area :text, placeholder: 'なにたべた？'
        = f.file_field :image
        = f.submit '投稿する'
  %footer

releases/20201029081621/releases/20201026220654/releases/20201017104702/app/views/posts/try.html.haml
.contents.row
  - @tweets.each do |tweet|
    .content_post{:style => "background-image: url(#{tweet.image});"}
      %p= tweet.text
      %span.name
        = tweet.name